### ISSUE TITLE
Build and Deploy to maven repo

### ISSUE THREAD

**Issue by sbonnick** [bodiam/markdown-to-asciidoc#23]
Hi, 

Is there a plan to deploy this to a maven repo? Jcenter or maven central?

I suspect more people will consume this library once it is released to a common repository.

Thanks,
-Stewart

**Comment by bodiam** [comment]
Hi @sbonnick, it's actually good enough for a 1.0 release, I've used it quite often now myself. Uploading to Jcenter or similar would be great, but I have to find out how to do it. If you have some steps available, I'll upload it!

**Comment by sbonnick** [comment]
Using the gradle plugin for bintray simplifies most of it: https://github.com/bintray/gradle-bintray-plugin

Although outdated, this article lays out the basics: http://androiddeving.blogspot.ca/2014/08/deploying-on-jcenter-bintray-how-to.html

If that dosn't work, let me know and I should be able to help!

**Comment by RobWin** [comment]
+1 :)

**Comment by RobWin** [comment]
Have a look at https://github.com/Swagger2Markup/swagger2markup/blob/master/build.gradle
and https://github.com/Swagger2Markup/swagger2markup/blob/master/gradle/publishing.gradle if you want to see how to do it with Gradle.

**Comment by bodiam** [comment]
Is this not enough? https://dl.bintray.com/erik-pragt/maven/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/

**Comment by RobWin** [comment]
At least JCenter would be great. You activate it in Bintray.

**Comment by bodiam** [comment]
https://jcenter.bintray.com/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/ ?

**Comment by RobWin** [comment]
Great. Thx.
Could you pelase can add it to your README :)

**Comment by bodiam** [comment]
Done :-)
