### ISSUE TITLE
Help needed using your library with Groovy (Problems with ASM?)

### ISSUE THREAD

**Issue by RobWin** [bodiam/markdown-to-asciidoc#24]
Hi Erik,

I'm using your great library in [Swagger2Markup](https://github.com/Swagger2Markup/swagger2markup) now.
It works fine so far, but I have some issues in my [swagger2markup-gradle-plugin](https://github.com/Swagger2Markup/swagger2markup-gradle-plugin). 

I get the following exception:

```
java.lang.RuntimeException: Error creating extended parser class: null

    at org.parboiled.Parboiled.createParser(Parboiled.java:58)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:61)
    at nl.jworks.markdown_to_asciidoc.Converter.convertMarkdownToAsciiDoc(Converter.java:42)
....
Caused by: java.lang.IllegalStateException
    at org.parboiled.transform.ParserClassNode.<init>(ParserClassNode.java:41)
    at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
    at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
    at org.parboiled.Parboiled.createParser(Parboiled.java:54)
    ... 17 more
```

`org.parboiled.transform.ParserClassNode`extends `org.objectweb.asm.tree.ClassNode`

When I look in Intellj at the decompiled code of  `ClassNode`, I can find the code snippet which seems to be executed.

```
public ClassNode() {
        this(327680);
        if(this.getClass() != class$org$objectweb$asm$tree$ClassNode) {
            throw new IllegalStateException();
        }
    }
```

Parboiled uses ASM 4.1 and when I look at the [source code](http://websvn.ow2.org/filedetails.php?repname=asm&path=%2Ftags%2FASM_4_1%2Fsrc%2Forg%2Fobjectweb%2Fasm%2Ftree%2FClassNode.java) I can't find this code snippet. 

As far as I know, Groovy uses ASM internally.

Did you ever faced similar issues with Groovy and ASM when using your library?
I'm using Gradle 2.12 which uses Groovy-all 2.4.4. But groovy-all brings ASM shaded.

Kind regards,

Robert

**Comment by RobWin** [comment]
@glaforge Can you help here? :)

**Comment by bodiam** [comment]
Hi Robert,

I'm sorry, but I have only used the converter from a Java environment, never from a Groovy one, so I'd have no idea.

Erik

**Comment by RobWin** [comment]
Ok. Thx.

**Comment by glaforge** [comment]
The error doesn't seem to be related to Groovy, so not sure I can be of much help.
Groovy indeed uses ASM too, but it's shaded, in its own package, so there's no possible clash with other ASM classes that could be on the classpath.

**Comment by RobWin** [comment]
@glaforge  Thx for having a look

**Comment by RobWin** [comment]
I created a pure Gradle/Groovy projects and a Spock test. And it works, too.
Very strange.

**Comment by RobWin** [comment]
I have created a small Gradle Plugin which converts Markdown to Asciidoc using your library and it works as well.
Means: The issue must have something to do with the transitive dependencies of Swagger2Markup??

**Comment by RobWin** [comment]
A pure Java JUnit test works when I remove the following in the Gradle script
``` 
//compile gradleApi()
//compile localGroovy()
```

**Comment by RobWin** [comment]
Now it becomes interesting.
When I run the Test in IntellJ using the Platform Test runner everything works.
If I use the Gradle Test runner, everything fails.

**Comment by RobWin** [comment]
A solution might be to shadow Parboiled, because ASM is often the cause of issues.

**Comment by kruffin** [comment]
As a workaround, I was able to get around the initial error by adding a more recent parboiled to the classpath and swagger2markup can now generate asciidoc format.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        ....
    	classpath group: 'org.parboiled', name: 'parboiled-java', version: '1.1.7'
    }
}
```

**Comment by RobWin** [comment]
Very nice. Would you like to create a PR?

**Comment by kruffin** [comment]
@RobWin I would, but I'm not too sure how to test local plugins (I added the above dependency to my current project's build.gradle). I think another option is for this project to use a pegdown 1.5+ version since it is supposed to be fixed in there too; according to your first linked parboiled issue.

**Comment by bodiam** [comment]
Is this still an issue with 1.1?
