### ISSUE TITLE
Converter will be used in Jamal

### ISSUE THREAD

**Issue by verhas** [bodiam/markdown-to-asciidoc#34]
This is not an issue, I just wanted to inform you that I use the converter in the next release of Jamal.

The Asciidoc plugin calls Jamal. Jamal processes the macros in the markdown input, saves the resulting MD file to disc, but also converts the md to Asciidoc and passes it back to the plugin. That way markdown files are displayed with Jamal macros executed and extended as Asciidoc files.

Jamal is at https://github.com/verhas/jamal

Please close this issue.

**Comment by bodiam** [comment]
Hi @verhas , never saw this message, thanks for sharing!

**Comment by verhas** [comment]
Sure thing. That release and several releases since then are out.  I recently used it in a live Demo at the Craft Conference 2023 Budapest editing a Markdown document in an Asccidoc editor and showing the formatted output.
